/**
 * scripts/seed-supabase.ts
 *
 * Serializes zones + agents + assignments for ALL 3 regions → SQL INSERT
 * Run: npx tsx scripts/seed-supabase.ts
 * Output: scripts/seed.sql
 */

import { writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

// ── Import region data ──────────────────────────────────────────
import { HCM_ZONES, HCM_AGENTS, HCM_ASSIGNMENTS, centroidOf } from './seed-hcm.js'
import { HUE_ZONES, HUE_AGENTS, HUE_ASSIGNMENTS, centroidOfHue } from './seed-hue.js'

// ── Hanoi data (inline, same as before) ─────────────────────────

const C0 = 105.72, C1 = 105.80, C2 = 105.88, C3 = 105.96
const R0 = 20.87,  R1 = 20.94,  R2 = 21.01,  R3 = 21.08, R4 = 21.15
const MC01 = (C0 + C1) / 2, MC12 = (C1 + C2) / 2, MC23 = (C2 + C3) / 2
const MR01 = (R0 + R1) / 2, MR12 = (R1 + R2) / 2
const MR23 = (R2 + R3) / 2, MR34 = (R3 + R4) / 2

function centroidOfHN(ring: number[][]): { lat: number; lng: number } {
  const pts = ring.slice(0, -1)
  const lat = pts.reduce((s, p) => s + p[1]!, 0) / pts.length
  const lng = pts.reduce((s, p) => s + p[0]!, 0) / pts.length
  return { lat: Math.round(lat * 1000) / 1000, lng: Math.round(lng * 1000) / 1000 }
}

const z01Ring = [[C0,R3],[MC01,R3],[MC01,MR34-0.005],[C1,MR34],[C1,R4],[MC01,R4+0.005],[C0,R4],[C0,MR34],[C0,R3]]
const z06Ring = [[C1,MR34],[MC01,MR34-0.005],[MC01,R3],[C1,R3],[C2,R3],[C2,R4],[C1,R4],[C1,MR34]]
const z04Ring = [[C2,R3],[MC23,R3],[C3,R3+0.01],[C3,MR34],[C3,R4],[MC23,R4-0.005],[C2,R4],[C2,R3]]
const z02Ring = [[C0,R2],[MC01,R2+0.005],[C1,R2],[C1,R3],[MC01,R3],[C0,R3],[C0,R2]]
const z05Ring = [[C1,R2],[MC12,R2],[C2,R2],[C2,MR23],[C2,R3],[C1,R3],[C1,MR23+0.005],[C1,R2]]
const z07Ring = [[C2,R2],[MC23,R2-0.005],[C3,R2],[C3,R3+0.01],[MC23,R3],[C2,R3],[C2,MR23],[C2,R2]]
const z03Ring = [[C0,R1],[MC01,R1],[C1,R1+0.005],[C1,R2],[MC01,R2+0.005],[C0,R2],[C0,R1]]
const z09Ring = [[C1,R1+0.005],[MC12,R1],[C2,R1],[C2,MR12],[C2,R2],[MC12,R2],[C1,R2],[C1,R1+0.005]]
const z08Ring = [[C2,R1],[MC23,R1+0.005],[C3,R1],[C3,R2],[MC23,R2-0.005],[C2,R2],[C2,MR12],[C2,R1]]
const z12Ring = [[C0,R0],[MC01,R0+0.005],[C1,R0],[C1,R1+0.005],[MC01,R1],[C0,R1],[C0,R0]]
const z10Ring = [[C1,R0],[MC12,R0],[C2,R0+0.005],[C2,R1],[MC12,R1],[C1,R1+0.005],[C1,R0]]
const z11Ring = [[C2,R0+0.005],[MC23,R0],[C3,R0],[C3,MR01],[C3,R1],[MC23,R1+0.005],[C2,R1],[C2,R0+0.005]]

const HN_ZONES = [
  { id: 'z01', name: 'Tây Hồ',       ring: z01Ring, activities: [['a01a','CUSTOMER',120],['a01b','ORDER',85]] },
  { id: 'z02', name: 'Cầu Giấy',      ring: z02Ring, activities: [['a02a','CUSTOMER',200],['a02b','ORDER',140],['a02c','REVENUE',5000]] },
  { id: 'z03', name: 'Nam Từ Liêm',   ring: z03Ring, activities: [['a03a','CUSTOMER',90],['a03b','ORDER',60]] },
  { id: 'z04', name: 'Long Biên',     ring: z04Ring, activities: [['a04a','CUSTOMER',310],['a04b','ORDER',210]] },
  { id: 'z05', name: 'Ba Đình',       ring: z05Ring, activities: [['a05a','CUSTOMER',180],['a05b','ORDER',130]] },
  { id: 'z06', name: 'Đống Đa',       ring: z06Ring, activities: [['a06a','CUSTOMER',75],['a06b','ORDER',45]] },
  { id: 'z07', name: 'Hai Bà Trưng',  ring: z07Ring, activities: [['a07a','CUSTOMER',250],['a07b','ORDER',170]] },
  { id: 'z08', name: 'Hoàng Mai',     ring: z08Ring, activities: [['a08a','CUSTOMER',290],['a08b','ORDER',200],['a08c','REVENUE',7500]] },
  { id: 'z09', name: 'Thanh Xuân',    ring: z09Ring, activities: [['a09a','CUSTOMER',220],['a09b','ORDER',150]] },
  { id: 'z10', name: 'Hà Đông',       ring: z10Ring, activities: [['a10a','CUSTOMER',160],['a10b','ORDER',110]] },
  { id: 'z11', name: 'Thanh Trì',     ring: z11Ring, activities: [['a11a','CUSTOMER',130],['a11b','ORDER',90]] },
  { id: 'z12', name: 'Hoài Đức',      ring: z12Ring, activities: [['a12a','CUSTOMER',95],['a12b','ORDER',65]] },
] as const

const HN_AGENTS = [
  { id: 'sa0', name: 'Nguyễn Văn Alpha', region: 'Tây-Bắc Hà Nội', capacity: 400 },
  { id: 'sa1', name: 'Trần Thị Beta',    region: 'Đông-Bắc Hà Nội', capacity: 500 },
  { id: 'sa2', name: 'Lê Quốc Gamma',   region: 'Đông-Nam Hà Nội', capacity: 600 },
  { id: 'sa3', name: 'Phạm Hữu Delta',  region: 'Tây-Nam Hà Nội', capacity: 350 },
] as const

const HN_ASSIGNMENTS = [
  ['z01',0,'sa0'],['z02',0,'sa0'],['z03',0,'sa0'],
  ['z04',1,'sa1'],['z05',1,'sa1'],['z06',1,'sa1'],
  ['z07',2,'sa2'],['z08',2,'sa2'],['z09',2,'sa2'],
  ['z10',3,'sa3'],['z11',3,'sa3'],['z12',3,'sa3'],
] as const

// ── Helpers ──────────────────────────────────────────────────────

function esc(s: string): string {
  return s.replace(/'/g, "''")
}

function toJsonb(v: unknown): string {
  return `'${JSON.stringify(v)}'::jsonb`
}

// ── Generate SQL ─────────────────────────────────────────────────

const lines: string[] = [
  '-- ═══════════════════════════════════════════════════════════════',
  '-- TERRIMAP SEED DATA — ALL 3 REGIONS',
  '-- Generated by scripts/seed-supabase.ts',
  `-- Date: ${new Date().toISOString().slice(0, 10)}`,
  '-- ═══════════════════════════════════════════════════════════════',
  '',
]

// ── All agents (3 regions) ──────────────────────────────────────
const allAgents = [
  ...HN_AGENTS.map(a => ({ ...a, regionId: 'region-hn' })),
  ...HCM_AGENTS.map(a => ({ ...a, regionId: 'region-hcm' })),
  ...HUE_AGENTS.map(a => ({ ...a, regionId: 'region-hue' })),
]

lines.push('-- Sales Agents (all regions)')
lines.push('INSERT INTO sales_agents (id, name, active_region, capacity, region_id) VALUES')
const agentLines = allAgents.map((a, i) =>
  `  ('${a.id}', '${esc(a.name)}', '${esc(a.region)}', ${a.capacity}, '${a.regionId}')${i < allAgents.length - 1 ? ',' : ''}`
)
lines.push(agentLines.join('\n') + '\nON CONFLICT (id) DO NOTHING;')

// ── All zones (3 regions) ───────────────────────────────────────
type ZoneData = { id: string; name: string; ring: readonly (readonly number[])[] | number[][]; activities: readonly (readonly [string, string, number])[] }

const allZones: Array<ZoneData & { regionId: string }> = [
  ...(HN_ZONES as unknown as ZoneData[]).map(z => ({ ...z, regionId: 'region-hn' })),
  ...(HCM_ZONES as unknown as ZoneData[]).map(z => ({ ...z, regionId: 'region-hcm' })),
  ...(HUE_ZONES as unknown as ZoneData[]).map(z => ({ ...z, regionId: 'region-hue' })),
]

lines.push('')
lines.push('-- Zones (all regions)')
lines.push('INSERT INTO zones (id, name, status, polygon, centroid, region_id) VALUES')

const zoneInserts = allZones.map((z, i) => {
  const ring = z.ring.map(p => [...p])
  const polygon = { type: 'Polygon', coordinates: [ring] }
  const c = centroidOfHN(ring)
  const suffix = i < allZones.length - 1 ? ',' : ''
  return `  ('${z.id}', '${esc(z.name)}', 'unassigned', ${toJsonb(polygon)}, ${toJsonb(c)}, '${z.regionId}')${suffix}`
})
lines.push(zoneInserts.join('\n') + '\nON CONFLICT (id) DO NOTHING;')

// ── Activities ──────────────────────────────────────────────────
lines.push('')
lines.push('-- Activities (all regions)')
lines.push('INSERT INTO activities (id, zone_id, type, value) VALUES')

const actLines: string[] = []
for (const z of allZones) {
  for (const [id, type, value] of z.activities) {
    actLines.push(`  ('${id}', '${z.id}', '${type}', ${value})`)
  }
}
lines.push(actLines.join(',\n') + '\nON CONFLICT (id) DO NOTHING;')

// ── Assignments ─────────────────────────────────────────────────
const allAssignments = [
  ...HN_ASSIGNMENTS,
  ...HCM_ASSIGNMENTS,
  ...HUE_ASSIGNMENTS,
]

lines.push('')
lines.push('-- Assignments (all regions)')
lines.push('INSERT INTO assignments (zone_id, district_id, sales_agent_id) VALUES')
const aLines = allAssignments.map(([zid, did, said], i) =>
  `  ('${zid}', ${did}, '${said}')${i < allAssignments.length - 1 ? ',' : ''}`
)
lines.push(aLines.join('\n') + '\nON CONFLICT (zone_id) DO NOTHING;')

const sql = lines.join('\n')
console.log(sql)

const __dirname = dirname(fileURLToPath(import.meta.url))
const outPath = join(__dirname, 'seed.sql')
writeFileSync(outPath, sql, 'utf-8')
console.error(`\n✅ Seed SQL written to ${outPath}`)
console.error(`   HN: ${HN_ZONES.length} zones, ${HN_AGENTS.length} agents`)
console.error(`   HCM: ${HCM_ZONES.length} zones, ${HCM_AGENTS.length} agents`)
console.error(`   HUE: ${HUE_ZONES.length} zones, ${HUE_AGENTS.length} agents`)
console.error(`   Total: ${allZones.length} zones, ${allAgents.length} agents`)
